@extends('layouts.app')


@section('content')
 
 
 
 <!-- START HEADING GOOGLE API -->

 <section class="section-legal--title u-padding-lg pb-0">
    <h1 class="section-title text-center">Privacy Policy</h1>
  </section>
  <!-- END HEADING GOOGLE API -->

  <!-- START GOOGLE API POLICY  -->
  <section class="section-legal--content u-padding-lg pt-5">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10 col-12">
          <div class="card border-0 p-5">
            <div class="card-body">
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.

              We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.
              <!-- <a
                href="https://developers.google.com/terms/api-services-user-data-policy#additional_requirements_for_specific_api_scopes">
                Google API Services User Data Policy </a>, including the Limited Use requirements.
            </div> -->
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- END GOOGLE API POLICY -->

  <!-- START HEADING FACEBOOK API -->
  <section class="section-legal--title u-padding-lg pb-0">
    <h1 class="section-title text-center">Interpretation and Definitions</h1>
  </section>
  <!-- END HEADING FACEBOOK API -->

  <!-- START GOOGLE API POLICY  -->
  <section class="section-legal--content u-padding-lg pt-5">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10 col-12">
          <div class="card border-0 p-5">
            <div class="card-body">
              <h1 class="section-title">Interpretation</h1>
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
             
                <h1 class="section-title">Definitions</h1>

                <h2 class="legal-title">2. Affiliate</h2>
              <p class="legal-text">
                Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Health, House-75, Road-04, Block-B, Niketon, Gulshan, Dhaka-1212, Bangladesh.                </p>
              <h2 class="legal-title">3. Company </h2>
              <p class="legal-text">
                Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
                </p>
              <h2 class="legal-title">4. Cookies</h2>
              <p class="legal-text">
                a unique account created for You to access our Service or parts of our Service.
              </p>
              <h2 class="legal-title">5. Country </h2>
              <p class="legal-text">
                Country refers to: Bangladesh
              </p>
              <h2 class="legal-title">6. Device </h2>
              <p class="legal-text">
                Personal Data is any information that relates to an identified or identifiable individual.               
              
              <h2 class="legal-title">7.Service</h2>
              <p class="legal-text">
                Personal Data is any information that relates to an identified or identifiable individual.
              </p>
              <h2 class="legal-title">8. Service Provider</h2>
              <p class="legal-text">
                Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.

              </p>
              <h2 class="legal-title">9. Third-party Social Media Service</h2>
              <p class="legal-text">
                Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.

              </p>
              <h2 class="legal-title">10. Usage Data</h2>
              <p class="legal-text">
                Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                Website refers to Cikitsa International, accessible from
              </p>
              <h2 class="legal-title">11. Website</h2>
              <p class="legal-text">
                Website refers to Cikitsa International, accessible from<a href="https://cikitsainternational.com/">
                 cikitsainternational </a>
              </p>
              <p class="legal-text">
                You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
              </p>
             

            </div>
          </div>
          

        </div>
      </div>
    </div>

    
  </section>
  <!-- END FACEBOOK API POLICY -->

  <!-- start collecting parsonal data -->

  <section class="section-legal--content u-padding-lg pt-5">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10 col-12">
          <div class="card border-0 p-5">
            <div class="card-body">
              <h1 class="section-title">Collecting and Using Your Personal Data</h1>
              <h3>Types of Data Collected</h3>              
                <h1 class="section-title">Personal Data</h1>
                <p>Email address</p>
                <p>First name and last name</p>
                <p>Phone number</p>
                <p>Address, State, Province, ZIP/Postal code, City</p>
                <p>Usage Data</p>
              <!-- <p class="legal-text">
                While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:                <h2 class="legal-title">3. Company </h2>
              <p class="legal-text">
                Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
                </p> -->
              
            
              <h2 class="legal-title">Usage Data </h2>
              <p class="legal-text">
                Usage Data is collected automatically when using the Service.
              </p>
              
              <p class="legal-text">
                Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.               
              
             
              <p class="legal-text">
                When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
              </p>
              
              <p class="legal-text">
                We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
              </p>
              <h2 class="legal-title">Information from Third-Party Social Media Services</h2>
              <p class="legal-text">
                The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:
              </p>
              <h2 class="legal-title">10. Usage Data</h2>
              <div class="col-lg-3 col-md-4 col-sm-6 pb-lg-5 pb-3 ps-md-0 ps-4 mt-md-0 mt-4">
            

            </div>
          </div>

         

        </div>
      </div>
    </div>
    
    
  </section>
  @endsection

 